# Default CPU lowering pipeline.
#
# This is the fallback pipeline used by `ai_bench.mlir.cpu_pipeline`
# when no target/feature/dtype specific descriptor is found.
#
# The pipeline focuses on enabling end-to-end lowering for any modules
# to the MLIR LLVM IR dialect.
Pipeline:
  # Use standard C interface wrappers for functions.
  - pass: "func.func(llvm-request-c-wrappers)"

  # Bufferize.
  - pass: "eliminate-empty-tensors"
  - pass: "one-shot-bufferize{function-boundary-type-conversion=identity-layout-map bufferize-function-boundaries}"
  - pass: "drop-equivalent-buffer-results"
  - pass: "buffer-deallocation-pipeline"
  - pass: "convert-bufferization-to-memref"
  - pass: "cse"
  - pass: "canonicalize"

  # Lower to LLVM.
  - pass: "convert-linalg-to-loops"
  - pass: "math-expand-ops"
  - pass: "expand-strided-metadata"
  - pass: "canonicalize"

  - pass: "convert-vector-to-scf"
  - pass: "lower-affine"
  - pass: "convert-scf-to-cf"
  - pass: "convert-vector-to-llvm"
  - pass: "convert-math-to-libm"
  - pass: "convert-to-llvm"
  - pass: "reconcile-unrealized-casts"

  # Cleanup.
  - pass: "cse"
  - pass: "canonicalize"
