name: KernelBench Perf

on:
  workflow_dispatch:
    inputs:
      RUN_CPU_TORCH:
        description: "Run on CPU (PyTorch eager)"
        type: boolean
        default: false
      RUN_CPU_MLIR:
        description: "Run on CPU (MLIR)"
        type: boolean
        default: false
      RUN_XPU_TORCH:
        description: "Run on Intel GPU (PyTorch eager)"
        type: boolean
        default: true
      RUN_XPU_TORCH_COMPILE:
        description: "Run on Intel GPU (PyTorch compile)"
        type: boolean
        default: false
      RUN_XPU_TRITON:
        description: "Run on Intel GPU (Triton)"
        type: boolean
        default: false
      RUN_XPU_HELION:
        description: "Run on Intel GPU (Helion)"
        type: boolean
        default: false
      RUN_CUDA_TORCH:
        description: "Run on Nvidia GPU (PyTorch eager)"
        type: boolean
        default: false

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh

jobs:
  CPU-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_CPU_TORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        run: "${{ env.SRUN }} --partition=emr --time=0:15:00 --constraint=\"notrb\" -- \
            '${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -b torch'"

  CPU-MLIR:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_CPU_MLIR)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        run: "${{ env.SRUN }} --partition=emr --time=0:15:00 --constraint=\"notrb\" -- \
            '${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -b mlir'"

  XPU-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_XPU_TORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc B580
        run: "${{ env.SRUN }} --partition=b580 --time=0:15:00 -- \
            '${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -b torch'"

  XPU-PyTorch-Compile:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_XPU_TORCH_COMPILE)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc B580
        run: "${{ env.SRUN }} --partition=b580 --time=0:15:00 -- \
            '${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -b torch-compile'"

  XPU-Triton:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_XPU_TRITON)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc B580
        run: "${{ env.SRUN }} --partition=b580 --time=0:15:00 -- \
            '${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -b triton'"

  XPU-Helion:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_XPU_HELION)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc B580
        run: "${{ env.SRUN }} --partition=b580 --time=0:15:00 -- \
            '${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -b helion'"

  CUDA-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.RUN_CUDA_TORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Nvidia A100
        run: "${{ env.SRUN }} --partition=a100 --time=0:15:00 -- \
            '${{ github.workspace }}/infra/scripts/ci-cuda-run-kernel-bench.sh -b torch'"
