name: KernelBench Perf

on:
  workflow_dispatch:
    inputs:
      RUN_MODE:
        description: "Run mode"
        type: choice
        default: 'bench'
        options:
          - bench
          - ci
      AIBENCH_WARMUP:
        description: "Warmup iterations"
        type: number
        default: 10
      AIBENCH_REP:
        description: "Timed iterations"
        type: number
        default: 50
      AIBENCH_VARIANT:
        description: "Problem spec variant (optional)"
        type: string
        default: ''
      DEVICE_CPU:
        description: "Device: CPU"
        type: boolean
        default: false
      DEVICE_XPU:
        description: "Device: Intel GPU"
        type: boolean
        default: true
      XPU_NODE:
        description: "XPU node partition"
        type: choice
        default: 'b50'
        options:
          - b50
          - b70
      DEVICE_CUDA:
        description: "Device: Nvidia GPU"
        type: boolean
        default: false
      BACKEND_PYTORCH:
        description: "Backend: PyTorch (eager)"
        type: boolean
        default: true
      BACKEND_PYTORCH_COMPILE:
        description: "Backend: PyTorch (compile)"
        type: boolean
        default: false
      BACKEND_TRITON:
        description: "Backend: Triton"
        type: boolean
        default: false
      BACKEND_HELION:
        description: "Backend: Helion"
        type: boolean
        default: false
      BACKEND_MLIR:
        description: "Backend: MLIR"
        type: boolean
        default: false

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh

jobs:
  CPU-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CPU && inputs.BACKEND_PYTORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        run: "${{ env.SRUN }} --partition=emr --time=0:15:00 --constraint=\"notrb\" -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b torch'"

  CPU-PyTorch-Compile:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CPU && inputs.BACKEND_PYTORCH_COMPILE)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        env:
          TORCHINDUCTOR_MAX_AUTOTUNE: 1
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b torch-compile'"

  CPU-Triton:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CPU && inputs.BACKEND_TRITON)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b triton'"

  CPU-MLIR:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CPU && inputs.BACKEND_MLIR)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Emerald Rapids
        run: "${{ env.SRUN }} --partition=emr --time=0:15:00 --constraint=\"notrb\" -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b mlir'"

  XPU-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_PYTORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc Pro (selected)
        run: "${{ env.SRUN }} --partition=${{ inputs.XPU_NODE }} --time=0:30:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b torch'"

  XPU-PyTorch-Compile:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_PYTORCH_COMPILE)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc Pro (selected)
        run: "${{ env.SRUN }} --partition=${{ inputs.XPU_NODE }} --time=0:30:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b torch-compile'"

  XPU-Triton:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_TRITON)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc Pro (selected)
        run: "${{ env.SRUN }} --partition=${{ inputs.XPU_NODE }} --time=0:30:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b triton'"

  XPU-Helion:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_HELION)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc Pro (selected)
        run: "${{ env.SRUN }} --partition=${{ inputs.XPU_NODE }} --time=0:30:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b helion'"

  XPU-Check-LLVM:
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_MLIR)
    uses: ./.github/workflows/build-llvm.yml
    secrets: inherit

  XPU-MLIR:
    runs-on: pcl-tiergarten
    needs: XPU-Check-LLVM
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_XPU && inputs.BACKEND_MLIR)

    steps:
      - uses: actions/checkout@v5

      - name: Intel Arc Pro (selected)
        run: "${{ env.SRUN }} --partition=${{ inputs.XPU_NODE }} --time=0:30:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-xpu-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b mlir'"

  CUDA-PyTorch:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CUDA && inputs.BACKEND_PYTORCH)

    steps:
      - uses: actions/checkout@v5

      - name: Nvidia H100
        run: "${{ env.SRUN }} --partition=h100 --time=0:15:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cuda-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b torch'"

  CUDA-Triton:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CUDA && inputs.BACKEND_TRITON)

    steps:
      - uses: actions/checkout@v5

      - name: Nvidia H100
        run: "${{ env.SRUN }} --partition=h100 --time=0:15:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cuda-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b triton'"

  CUDA-Helion:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.DEVICE_CUDA && inputs.BACKEND_HELION)

    steps:
      - uses: actions/checkout@v5

      - name: Nvidia H100
        run: "${{ env.SRUN }} --partition=h100 --time=0:15:00 -- \
            'AIBENCH_WARMUP=${{ inputs.AIBENCH_WARMUP }} AIBENCH_REP=${{ inputs.AIBENCH_REP }} AIBENCH_VARIANT=${{ inputs.AIBENCH_VARIANT }} ${{ github.workspace }}/infra/scripts/ci-cuda-run-kernel-bench.sh -m ${{ inputs.RUN_MODE }} -b helion'"
